site:
  domain: "example.com" # haven't use yet.
  secure:
    pepper: "custom.pepper.value"
    jwt:
      enable: true # 开启jwt保护mutation操作,影响所有@hasLogin指令标记的type
      key: "some.secret.key"

database:
  host: "localhost"
  dbname: "golbat"
  port: 5432
  user: "golbat"
  password: "golbat"
  debug: false
