version: "3.7"

services:
  db:
    image: "postgres:12-alpine"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: golbat
      POSTGRES_USER: golbat
      POSTGRES_PASSWORD: golbat

  golb:
    image: "nediiii/golb"
    restart: "always"
    depends_on:
      - db
    ports:
      - "8090:8090"
    environment:
      GIN_MODE: "release"

volumes:
  postgres-data:
