version: "3.7"

services:
  # https://hub.docker.com/_/postgres
  db:
    image: "postgres:12-alpine"
    restart: "always"
    ports:
      - "5432:5432"
    # volumes:
    # - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: golbat
      POSTGRES_USER: golbat
      POSTGRES_PASSWORD: golbat
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 2345:8080
# volumes:
# postgres-data:
