// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// The `Setting` type, represents the request for setting a setting.
type InputSetting struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}
